### ISSUE TITLE
about pokeVision

### ISSUE THREAD

**Issue by oujinlong** [gbmksquare/Pokemon-GO-Controller-for-Mac#1]
Does pokevision still works now?

**Comment by gbmksquare** [comment]
Unfortunately PokéVision doesn't work anymore.
The button has been removed from the Mac app.
I'll update the docs soon.

**Comment by gbmksquare** [comment]
Commit d259a0e
Commit 07f8483

**Comment by oujinlong** [comment]
any poke map still works now?

**Comment by gbmksquare** [comment]
I'm not sure but I think they are all disabled now.
