### ISSUE TITLE
working in vmware?

### ISSUE THREAD

**Issue by bunnlose** [gbmksquare/Pokemon-GO-Controller-for-Mac#2]
I'm currently browsing for fun stuff to try with my pokemon, and using Xcode certainly is one of the coolest things, not just rooting your phone getting banned in the process. I currently haven't got a mac. so I'm running OS X and Xcode in vmware. this works fine for making small script having your toon take a walk in the park. 
Unfortunately i was not able to run this on the system. Im getting some errors talking about the lack of hardware accelerator for GL pixel format. Im guessing its because I'm not able to get full functionality of the video card into vmware. 
Any idea for a workaround?

greets from norway

**Comment by gbmksquare** [comment]
I’m not sure how to fix that problem. More importantly, even if you use Xcode to simulate location, if Pokemon Go app detects you are jumping locations (for example, from New York to London), you will still get banned.

For another option, you can check this out!
https://github.com/kahopoon/Pokemon-Go-Controller
